'use client'
import {Nunito} from 'next/font/google'
import {usePathname} from 'next/navigation'
import {useEffect} from 'react'
import './globals.css'
import Script from "next/script";

// export const metadata = {
// 	title: 'Next.js',
// 	description: 'Generated by Next.js',
// }
const montserrat = Nunito({subsets: ['latin']})

export default function RootLayout({children}) {
    const pathname = usePathname()
    useEffect(() => {
        // Check if the current route matches '/admin'
        if (pathname.startsWith('/admin')) {
            // Load external stylesheets
            const fontAwesomeLink = document.createElement('link')
            fontAwesomeLink.rel = 'stylesheet'
            fontAwesomeLink.href = '/plugins/fontawesome-free/css/all.min.css'
            document.head.appendChild(fontAwesomeLink)

            const overlayScrollbarsLink = document.createElement('link')
            overlayScrollbarsLink.rel = 'stylesheet'
            overlayScrollbarsLink.href =
                '/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'
            document.head.appendChild(overlayScrollbarsLink)

            const adminLteLink = document.createElement('link')
            adminLteLink.rel = 'stylesheet'
            adminLteLink.href =
                'https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/css/adminlte.min.css'
            document.head.appendChild(adminLteLink)

            // Cleanup function
            return () => {
                document.head.removeChild(fontAwesomeLink)
                document.head.removeChild(overlayScrollbarsLink)
                document.head.removeChild(adminLteLink)
            }
        }
    }, [pathname])

    return (
        <html lang='en'>

        <body
            className={`${montserrat.className} sidebar-mini layout-fixed layout-navbar-fixed sidebar-collapse wrapper`}
        >
        {children}
        {/*<script src='https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/js/adminlte.min.js'/>*/}
        {/*<script src='https://code.jquery.com/jquery-3.6.0.min.js'/>*/}
        </body>
        </html>
    )
}
