import { Montserrat } from 'next/font/google'
import './globals.css'

export const metadata = {
	title: 'Next.js',
	description: 'Generated by Next.js',
}

const montserrat = Montserrat({ subsets: ['latin'] })

export default function RootLayout({ children }) {
	return (
		<html  lang='en'>
			<head>
				<link
					rel='stylesheet'
					href='/plugins/fontawesome-free/css/all.min.css'
				/>
				<link
					rel='stylesheet'
					href='/plugins/overlayScrollbars/css/OverlayScrollbars.min.css'
				/>
				<link
					rel='stylesheet'
					href='https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/css/adminlte.min.css'
				></link>
				<script
					defer
					src='https://code.jquery.com/jquery-3.6.0.min.js'
				></script>

				<script
					defer
					src='https://cdn.jsdelivr.net/npm/admin-lte@3.2/dist/js/adminlte.min.js'
				></script>
			</head>
			<body
			
				className={`${montserrat.className} sidebar-mini layout-fixed layout-navbar-fixed dark-mode sidebar-collapse wrapper`}
			>
				{children}
			</body>
		</html>
	)
}
